# render.yaml
services:
  - type: web
    name: anagram-game
    env: python
    buildCommand: cd backend_FASTAPI_mongodb && pip install -r requirements.txt
    startCommand: cd backend_FASTAPI_mongodb && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: anagram_game
